document.addEventListener('DOMContentLoaded', () => {
    const jokeContainer = document.getElementById('joke-container');

    // Array of jokes
    let jk = [
        `Why don't skeletons fight each other? They don't have the guts.`, 
`I told my wife she was drawing her eyebrows too high. She looked surprised.`, 
`Why don't programmers like nature? It has too many bugs.`, 
`Why did the scarecrow win an award? Because he was outstanding in his field!`, 
`I'm reading a book on anti-gravity. It's impossible to put down!`, 
`Why don't some couples go to the gym? Because some relationships don't work out.`, 
`Parallel lines have so much in common. It’s a shame they’ll never meet.`, 
`Why don’t scientists trust atoms? Because they make up everything!`, 
`I would tell you a joke about an elevator, but it’s an uplifting experience.`, 
`Why do cows have hooves instead of feet? Because they lactose.`, 
`I used to play piano by ear, but now I use my hands.`, 
`Did you hear about the mathematician who’s afraid of negative numbers? He’ll stop at nothing to avoid them.`, 
`Why don’t oysters donate to charity? Because they are shellfish.`, 
`I told my computer I needed a break, and now it won’t stop sending me Kit-Kats.`, 
`How do you organize a space party? You planet.`, 
`What do you call fake spaghetti? An impasta!`, 
`I once told a chemistry joke, but there was no reaction.`, 
`Why did the coffee file a police report? It got mugged.`, 
`I asked the librarian if the library had any books on paranoia. She whispered, "They're right behind you."`, 
`Why did the golfer bring extra pants? In case he got a hole in one.`, 
 `I told my computer I needed a break, and now it won’t stop sending me Kit-Kats.`, 
`How does a penguin build its house? Igloos it together.`, 
`What do you call a fake noodle? An impasta.`, 
`Why don’t some couples go to the gym? Because some relationships don’t work out.`, 
`Why did the scarecrow win an award? Because he was outstanding in his field.`, 
`Why did the bicycle fall over? It was two-tired.`, 
`I’m reading a book on anti-gravity. It’s impossible to put down.`, 
`I’m on a seafood diet. I see food and I eat it.`, 
`I used to be a baker, but I couldn't make enough dough.`, 
`Why was the math book sad? It had too many problems.`, 
`Why don’t eggs tell jokes? They’d crack each other up.`, 
`What do you get if you cross a snowman and a vampire? Frostbite.`, 
`I told my wife she should embrace her mistakes. She gave me a hug.`, 
`I would tell a chemistry joke, but all the good ones Argon.`, 
`I used to have a job at a calendar factory, but I got the sack because I took a couple of days off.`, 
`Why are skeletons so calm? Because nothing gets under their skin.`, 
`What do you call an alligator in a vest? An investigator.`, 
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`, 
`Why don’t seagulls fly over the bay? Because then they’d be bay-gulls.`, 
`I’m terrified of elevators, so I’m going to start taking steps to avoid them.`, 
`Why did the tomato turn red? Because it saw the salad dressing.`, 
`I used to play piano by ear, but now I use my hands.`, 
`What do you get when you cross a snowman and a dog? Frostbite.`, 
`I couldn’t figure out why the baseball kept getting bigger. Then it hit me.`, 
`Why do bees have sticky hair? Because they use honeycombs.`, 
`I asked the librarian if the library had any books on paranoia. She whispered, "They're right behind you."`, 
`What do you call a fish with no eyes? Fsh.`, 
`Why don’t oysters donate to charity? Because they are shellfish.`, 
`I’m no good at math, but I can count on you.`, 
`What do you call a magic dog? A labracadabrador.`, 
`Why don’t koalas count as bears? They don’t have the right koalafications.`, 
`I tried to catch fog yesterday. Mist.`, 
`I wanted to be a doctor, but I didn’t have the patients.`, 
`Why did the golfer bring extra pants? In case he got a hole in one.`, 
`What did the buffalo say to his son when he left for college? Bison.`, 
`Why did the invisible man turn down the job offer? He couldn’t see himself doing it.`, 
`I’m reading a book on teleportation. It’s bound to take me places.`, 
`I told my wife she should embrace her mistakes. She gave me a hug.`, 
`Why did the math book look sad? It had too many problems.`, 
`Why was the big cat disqualified from the race? Because it was a cheetah.`, 
`I’d tell you a joke about an elevator, but it’s an uplifting experience.`, 
`How do you organize a space party? You planet.`, 
`What do you call fake spaghetti? An impasta!`, 
`Why don’t some couples go to the gym? Because some relationships don’t work out.`, 
`I’m terrified of elevators, so I’m going to start taking steps to avoid them.`, 
`What do you call a bear with no teeth? A gummy bear.`, 
`Why did the mushroom go to the party alone? Because he was a fungi.`, 
`Why did the scarecrow become a successful neurosurgeon? Because he was outstanding in his field.`, 
`I don’t trust stairs because they’re always up to something.`, 
`Why did the bicycle fall over? Because it was two-tired.`, 
`Why did the tomato turn red? Because it saw the salad dressing.`, 
`I used to play piano by ear, but now I use my hands.`, 
`I wanted to be a baker, but I couldn’t make enough dough.`, 
`I asked my dog what’s two minus two. He said nothing.`, 
`I’m on a seafood diet. I see food and I eat it.`, 
`Why did the golfer bring extra pants? In case he got a hole in one.`, 
`Why did the scarecrow win an award? Because he was outstanding in his field.`, 
`I would tell a chemistry joke, but all the good ones Argon.`, 
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`, 
`Why don’t seagulls fly over the bay? Because then they’d be bay-gulls.`, 
`Why did the coffee file a police report? It got mugged.`, 
`I’m reading a book on anti-gravity. It’s impossible to put down.`, 
`Why was the math book sad? It had too many problems.`, 
`Why don’t skeletons fight each other? They don’t have the guts.`, 
`Why did the golfer bring extra pants? In case he got a hole in one.`, 
`Why don’t programmers like nature? It has too many bugs.`, 
`What do you call cheese that isn't yours? Nacho cheese.`, 
`What’s orange and sounds like a parrot? A carrot.`, 
`I couldn’t figure out why the baseball kept getting larger. Then it hit me.`, 
`Parallel lines have so much in common. It’s a shame they’ll never meet.`, 
`Why do cows wear bells? Because their horns don’t work.`, 
`Why don’t some couples go to the gym? Because some relationships don’t work out.`, 
`Why don’t eggs tell jokes? They’d crack each other up.`, 
`What do you get if you cross a snowman and a vampire? Frostbite.`, 
`I used to have a job at a calendar factory, but I got the sack because I took a couple of days off.`, 
`What do you call an alligator in a vest? An investigator.`, 
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`, 
`Why don’t seagulls fly over the bay? Because then they’d be bay-gulls.`, 
`Why was the big cat disqualified from the race? Because it was a cheetah.`, 
`I’m no good at math, but I can count on you.`, 
`What do you call a fish with no eyes? Fsh.`, 
`Why don’t oysters donate to charity? Because they are shellfish.`, 
`Why are skeletons so calm? Because nothing gets under their skin.`, 
`I told my computer I needed a break, and now it won’t stop sending me Kit-Kats.`, 
`How does a penguin build its house? Igloos it together.`, 
`What do you call a fake noodle? An impasta.`, 
`Why did the scarecrow win an award? Because he was outstanding in his field.`, 
`Why did the bicycle fall over? It was two-tired.`, 
`What did the buffalo say to his son when he left for college? Bison.`, 
`Why don’t skeletons fight each other? They don’t have the guts.`, 
`Why don’t scientists trust atoms? Because they make up everything.`, 
`Why did the scarecrow win an award? Because he was outstanding in his field.`, 
`I told my wife she was drawing her eyebrows too high. She looked surprised.`, 
`I threw a boomerang a few years ago. I now live in constant fear.`, 
`Why don’t skeletons fight each other? They don’t have the guts.`, 
`What do you call cheese that isn't yours? Nacho cheese.`, 
`Parallel lines have so much in common. It’s a shame they’ll never meet.`, 
`I would tell you a construction joke, but I’m still working on it.`, 
`Why do cows wear bells? Because their horns don’t work.`, 
`I couldn’t figure out why the baseball kept getting larger. Then it hit me.`, 
`Why don’t programmers like nature? It has too many bugs.`, 
`What’s orange and sounds like a parrot? A carrot.`, 
`I told my computer I needed a break, and now it won’t stop sending me Kit-Kats.`, 
`How does a penguin build its house? Igloos it together.`, 
`What do you call a fake noodle? An impasta.`, 
`Why don’t some couples go to the gym? Because some relationships don’t work out.`, 
`Why did the tomato turn red? Because it saw the salad dressing.`, 
`I’m reading a book on anti-gravity. It’s impossible to put down.`, 
`I’m on a seafood diet. I see food and I eat it.`, 
`I used to be a baker, but I couldn't make enough dough.`, 
`Why was the math book sad? It had too many problems.`, 
`Why did the golfer bring extra pants? In case he got a hole in one.`, 
`What did the buffalo say to his son when he left for college? Bison.`, 
`Why don’t seagulls fly over the bay? Because then they’d be bay-gulls.`, 
`I’m terrified of elevators, so I’m going to start taking steps to avoid them.`, 
`Why did the coffee file a police report? It got mugged.`, 
`I’m reading a book on anti-gravity. It’s impossible to put down.`, 
`Why did the invisible man turn down the job offer? He couldn’t see himself doing it.`, 
`What do you call a bear with no teeth? A gummy bear.`, 
`What do you call a fish with no eyes? Fsh.`, 
`Why don’t oysters donate to charity? Because they are shellfish.`, 
`Why don’t eggs tell jokes? They’d crack each other up.`, 
`I wanted to be a doctor, but I didn’t have the patients.`, 
`I’m no good at math, but I can count on you.`, 
`Why was the big cat disqualified from the race? Because it was a cheetah.`, 
`Why don’t koalas count as bears? They don’t have the right koalafications.`, 
`Why did the golfer bring extra pants? In case he got a hole in one.`, 
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`, 
`Why did the golfer bring three pairs of pants? Just in case he got a hole in one.`, 
`Why was the broom late? It swept in.`, 
`Why was the broom tired? It swept all night.`, 
`Why did the broom go to school? It wanted to sweep up knowledge.`, 
`Why did the broom start a band? It wanted to clean up the charts.`, 
`Why don’t skeletons fight each other? They don’t have the guts.`, 
`Why don’t skeletons dance? They don’t have any body to dance with.`, 
`Why don’t skeletons go on vacation? They have no body to go with.`, 
`Why don’t skeletons play football? They don’t have the guts.`, 
`Why don’t skeletons play hide and seek? They always get found.`, 
`Why don’t skeletons play cards? They don’t have any skin in the game.`, 
`Why don’t skeletons wear hats? They don’t have any brains to keep warm.`, 
`Why don’t skeletons wear socks? They have no feet to wear them on.`, 
`Why don’t skeletons wear shoes? They have no soles.`, 
`Why don’t skeletons wear sunglasses? They don’t have any eyeballs.`, 
`Why don’t skeletons wear clothes? They don’t have any body to wear them on.`, 
`Why don’t skeletons eat? They don’t have any stomachs.`, 
`Why don’t skeletons drink? They don’t have any thirst.`, 
`Why don’t skeletons cry? They don’t have any tear ducts.`, 
`Why don’t skeletons laugh? They don’t have any funny bones.`, 
`Why don’t skeletons talk? They don’t have any tongues.`, 
`Why don’t skeletons sing? They don’t have any vocal cords.`, 
`Why don’t skeletons whistle? They don’t have any lips.`, 
`Why don’t skeletons sneeze? They don’t have any noses.`, 
`Why don’t skeletons blink? They don’t have any eyelids.`, 
`Why don’t skeletons yawn? They don’t have any jaws.`, 
`Why don’t skeletons shiver? They don’t have any nerves.`, 
`Why don’t skeletons breathe? They don’t have any lungs.`, 
`Why don’t skeletons think? They don’t have any brains.`, 
`Why don’t skeletons love? They don’t have any hearts.`, 
`Why don’t skeletons hate? They don’t have any emotions.`, 
`Why don’t skeletons smile? They don’t have any teeth.`, 
`Why don’t skeletons frown? They don’t have any expressions.`, 
`Why don’t skeletons laugh? They don’t have any voices.`, 
`Why don’t skeletons scream? They don’t have any mouths.`, 
`Why don’t skeletons shout? They don’t have any volume.`, 
`Why don’t skeletons whisper? They don’t have any secrets.`, 
`Why don’t skeletons sing? They don’t have any songs.`, 
`Why don’t skeletons dance? They don’t have any rhythm.`, 
`Why don’t skeletons jump? They don’t have any springs.`, 
`Why don’t skeletons run? They don’t have any muscles.`, 
`Why don’t skeletons walk? They don’t have any legs.`, 
`Why don’t skeletons sit? They don’t have any bones to rest on.`, 
`Why don’t skeletons stand? They don’t have any feet to stand on.`, 
`Why don’t skeletons sleep? They don’t have any dreams.`, 
`Why don’t skeletons eat popcorn? They don’t have any hands to hold it with.`, 
`Why don’t skeletons drink soda? They don’t have any throats to swallow it with.`, 
`Why don’t skeletons eat pizza? They don’t have any mouths to chew it with.`, 
`Why don’t skeletons eat cake? They don’t have any forks to eat it with.`, 
`Why don’t skeletons eat ice cream? They don’t have any spoons to scoop it with.`, 
`Why don’t skeletons eat soup? They don’t have any bowls to slurp it from.`, 
`Why don’t skeletons eat cereal? They don’t have any milk to pour over it.`, 
`Why don’t skeletons eat candy? They don’t have any wrappers to unwrap it with.`, 
`Why don’t skeletons eat chocolate? They don’t have any mouths to savor it with.`, 
`Why don’t skeletons eat burgers? They don’t have any buns to bite into.`, 
`Why don’t skeletons eat fries? They don’t have any ketchup to dip them in.`, 
`Why did the bicycle fall over? Because it was two-tired.`, 
`What do you call a fish wearing a crown? A kingfish.`, 
`Why did the golfer wear two pairs of pants? In case he got a hole in one.`, 
`Why don’t some couples go to the gym? Because some relationships don’t work out.`, 
`Why did the tomato blush? Because it saw the salad dressing.`, 
`What do you call fake spaghetti? An impasta.`, 
`Why can’t you give Elsa a balloon? Because she’ll let it go.`, 
`What do you call a snowman with a six-pack? An abdominal snowman.`, 
`Why did the picture go to jail? Because it was framed.`, 
`Why don’t you ever see elephants hiding in trees? Because they’re so good at it.`, 
`Why was the math book sad? It had too many problems.`, 
`What did one wall say to the other wall? “I’ll meet you at the corner.”`, 
`Why don’t skeletons fight each other? They don’t have the guts.`, 
`Why don’t scientists trust atoms? Because they make up everything.`, 
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`, 
`Why was the broom late? It swept in.`, 
`What do you get when you cross a snowman and a vampire? Frostbite.`, 
`Why did the scarecrow win an award? Because he was outstanding in his field.`, 
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`, 
`What do you call a pile of cats? A meowtain.`, 
`Why did the computer go to the doctor? It had a virus.`, 
`What do you call cheese that isn’t yours? Nacho cheese.`, 
`Why do cows have hooves instead of feet? Because they lactose.`, 
`What did the fish say when it hit the wall? Dam.`, 
`Why can’t you hear a pterodactyl in the bathroom? Because it has a silent pee.`, 
`Why did the belt go to jail? Because it held up a pair of pants.`, 
`What do you call a dog magician? A labracadabrador.`, 
`Why did the cookie go to the doctor? Because it felt crummy.`, 
`Why don’t some couples go to the gym? Because some relationships don’t work out.`, 
`Why do ducks have tail feathers? To cover their buttquacks.`, 
`Why don’t some couples go to the gym? Because some relationships don’t work out.`, 
`Why did the scarecrow win an award? Because he was outstanding in his field.`, 
`What do you call a can opener that doesn’t work? A can’t opener.`, 
`Why don’t scientists trust atoms? Because they make up everything.`, 
`What do you call a snowman with a six-pack? An abdominal snowman.`, 
`Why was the math book sad? It had too many problems.`, 
`What did one wall say to the other wall? “I’ll meet you at the corner.”`, 
`What do you call fake spaghetti? An impasta.`, 
`Why did the tomato turn red? Because it saw the salad dressing.`, 
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`, 
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`, 
`Why was the broom late? It swept in.`, 
`What do you get when you cross a snowman and a vampire? Frostbite.`, 
`Why don’t skeletons fight each other? They don’t have the guts.`, 
`Why did the scarecrow win an award? Because he was outstanding in his field.`, 
`Why don’t some couples go to the gym? Because some relationships don’t work out.`, 
`Why did the bicycle fall over? Because it was two-tired.`, 
`What do you call a fish wearing a crown? A kingfish.`, 
`Why did the golfer wear two pairs of pants? In case he got a hole in one.`, 
`Why can’t you give Elsa a balloon? Because she’ll let it go.`, 
`Why did the picture go to jail? Because it was framed.`, 
`What do you call a snowman with a six-pack? An abdominal snowman.`, 
`Why did the tomato blush? Because it saw the salad dressing.`, 
`What do you call fake spaghetti? An impasta.`, 
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`, 
`Why don’t skeletons fight each other? They don’t have the guts.`, 
`Why did the bicycle fall over? Because it was two-tired.`, 
`What do you call a fish wearing a crown? A kingfish.`, 
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`, 
`Why did the computer go to the doctor? It had a virus.`, 
`Why did the belt go to jail? Because it held up a pair of pants.`, 
`What do you call a dog magician? A labracadabrador.`, 
`Why did the cookie go to the doctor? Because it felt crummy.`, 
`Why do ducks have tail feathers? To cover their buttquacks.`, 
`Why was the math book sad? It had too many problems.`, 
`What did one wall say to the other wall? “I’ll meet you at the corner.”`, 
`What do you call cheese that isn’t yours? Nacho cheese.`, 
`Why do cows have hooves instead of feet? Because they lactose.`, 
`What did the fish say when it hit the wall? Dam.`, 
`Why can’t you hear a pterodactyl in the bathroom? Because it has a silent pee.`, 
`Why did the scarecrow win an award? Because he was outstanding in his field.`, 
`Why don’t some couples go to the gym? Because some relationships don’t work out.`, 
`Why did the picture go to jail? Because it was framed.`, 
`What do you call a snowman with a six-pack? An abdominal snowman.`, 
`Why did the tomato blush? Because it saw the salad dressing.`, 
`What do you call fake spaghetti? An impasta.`, 
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`, 
`Why don’t skeletons fight each other? They don’t have the guts.`, 
`Why did the bicycle fall over? Because it was two-tired.`, 
`What do you call a fish wearing a crown? A kingfish.`, 
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`, 
`Why was the broom late? It swept in.`, 
`What do you get when you cross a snowman and a vampire? Frostbite.`, 
`Why don’t scientists trust atoms? Because they make up everything.`, 
`Why don’t skeletons fight each other? They don’t have the guts.`, 
`Why don’t some couples go to the gym? Because some relationships don’t work out.`, 
`Why did the bicycle fall over? Because it was two-tired.`, 
`What do you call a fish wearing a crown? A kingfish.`, 
`Why did the golfer wear two pairs of pants? In case he got a hole in one.`, 
`Why can’t you give Elsa a balloon? Because she’ll let it go.`, 
`Why did the picture go to jail? Because it was framed.`, 
`What do you call a snowman with a six-pack? An abdominal snowman.`, 
`Why did the tomato blush? Because it saw the salad dressing.`, 
`What do you call fake spaghetti? An impasta.`, 
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`, 
`Why don’t skeletons fight each other? They don’t have the guts.`, 
`Why did the computer go to the doctor? It had a virus.`, 
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`, 
`What do you call a pile of cats? A meowtain.`, 
`Why don’t some couples go to the gym? Because some relationships don’t work out.`, 
`Why did the scarecrow win an award? Because he was outstanding in his field.`,
`Why don't skeletons fight each other? They don't have the guts.`,
`What do you call fake spaghetti? An impasta.`,
`Why did the bicycle fall over? It was two-tired.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why don't seagulls fly over the bay? Because then they'd be bagels.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why was the math book sad? It had too many problems.`,
`Why can't your nose be 12 inches long? Because then it would be a foot.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`Why don't eggs tell jokes? They might crack up.`,
`Why did the computer go to the doctor? It had a virus.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`What do you call a belt made of watches? A waist of time.`,
`What do you call a fish wearing a crown? A kingfish.`,
`Why did the student eat his homework? Because the teacher told him it was a piece of cake.`,
`Why did the picture go to jail? Because it was framed.`,
`Why was the broom late? It swept in.`,
`Why do cows wear bells? Because their horns don’t work.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t elephants use computers? Because they’re afraid of the mouse.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`What’s orange and sounds like a parrot? A carrot.`,
`Why don’t scientists trust atoms? Because they make up everything.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`Why do bicycles fall over? Because they are two-tired.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why was the math book sad? It had too many problems.`,
`Why did the computer go to the doctor? It had a virus.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`Why did the picture go to jail? Because it was framed.`,
`Why was the broom late? It swept in.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why don’t scientists trust atoms? Because they make up everything.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why did the scarecrow win an award? Because he was outstanding in his field.`,
`Why did the bicycle fall over? It was two-tired.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why can’t your nose be 12 inches long? Because then it would be a foot.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call a pile of cats? A meowtain.`,
`Why did the computer go to the doctor? It had a virus.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why did the scarecrow win an award? Because he was outstanding in his field.`,
`Why did the bicycle fall over? It was two-tired.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why can’t your nose be 12 inches long? Because then it would be a foot.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call a pile of cats? A meowtain.`,
`Why did the computer go to the doctor? It had a virus.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
`Why was the math book sad? It had too many problems.`,
`Why did the belt get arrested? It was holding up a pair of pants.`,
`What do you call a snowman with a six-pack? An abdominal snowman.`,
`Why don’t skeletons fight each other? They don’t have the guts.`,
`What do you call a can opener that doesn’t work? A can’t opener.`,
`Why don’t eggs tell jokes? They might crack up.`,
`Why did the cookie go to the doctor? Because it felt crummy.`,
`What did one ocean say to the other ocean? Nothing, they just waved.`,
`Why don’t some couples go to the gym? Because some relationships don’t work out.`,
`What do you call fake spaghetti? An impasta.`,
`Why don’t seagulls fly over the bay? Because then they’d be bagels.`,
`What do you get when you cross a snowman and a vampire? Frostbite.`,
`Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
`Why do cows wear bells? Because their horns don’t work.`,
`Why did the picture go to jail? Because it was framed.`,
`Why did the tomato turn red? Because it saw the salad dressing.`,
    ];

    if (jk.length === 0) {
        jokeContainer.textContent = "No jokes available!";
        return;
    }

    // Generate a random index to select a joke
    let currentIndex = Math.floor(Math.random() * jk.length);

    // Optionally, store the last index to avoid repetition (if needed)
    let previousIndex = -1;
    
    // Ensure new joke is different from the previous one
    while (jk.length > 1 && currentIndex === previousIndex) {
        currentIndex = Math.floor(Math.random() * jk.length);
    }

    // Store the current index as previous for next refresh
    previousIndex = currentIndex;

    // Display the joke
    jokeContainer.textContent = jk[currentIndex];
});
